jobs:
  generateReadme:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      run: 'git config user.email mag@nordicsemi.no

        git config user.name "Github Action"

        VERSION=`git describe --tags --abbrev=0`

        VERSION=`./moustache/split.sh $VERSION`

        rm -f ./README.md

        VERSION=$VERSION ./moustache/mo ./moustache/README.mo > ./README.md

        git add .

        git diff-index --quiet HEAD || git commit -m "Update readme to version=$VERSION"
        && git push

        '
      shell: bash
name: Generate README.md
on:
  repository_dispatch:
    types: trigger-ga___generate-readme.yml
